# - setup:
#   register: my_setup
# - debug:
#     msg: "{{ my_setup }}"

- name: Gather the rpm package facts
  package_facts:
    manager: auto

# - name: Print the rpm package facts
#   debug:
#     var: ansible_facts.packages

- name: "Get all GIT packages"
  debug:
    msg: "{{ item }}
    Version: {{ ansible_facts.packages[item][0]['version'] }}
    Release: {{ ansible_facts.packages[item][0]['release'] }}"
  loop: "{{ ansible_facts.packages | list | select('match', 'git') | list }}"

